// Mağazaya özel TEK dosya: yeni müşteri = bu dosyayı kopyala, bilgileri ve ürünleri değiştir, img/ klasörüne görselleri koy.
window.MAGAZA = {
  ad: "Mira Mobilya",
  slogan: "Evinize göre üretilen mobilya",
  sehir: "Denizli",
  whatsapp: "905000000000", // ülke koduyla, boşluksuz (demo numarası)
  paraBirimi: "₺",
  teslimNotu: "Denizli merkeze ücretsiz teslimat ve kurulum. Diğer iller için kargo fiyatı sipariş onayında bildirilir.",
  kapak: { gorsel: "img/kapak.webp", ust: "2026 Koleksiyonu", baslik: "Sade, sıcak ve uzun ömürlü.", alt: "Ölçünüze ve kumaş seçiminize göre atölyemizde üretilir." },
  kategoriler: [
    { id: "oturma", ad: "Oturma Grubu" },
    { id: "yemek", ad: "Yemek Odası" },
    { id: "yatak", ad: "Yatak Odası" },
    { id: "depolama", ad: "TV ve Depolama" },
    { id: "sehpa", ad: "Sehpa" }
  ],
  urunler: [
    { id: "K-301", kat: "oturma", ad: "Lina Üçlü Kanepe", fiyat: 34900, eskiFiyat: 38900, gorsel: "img/kanepe-3lu.webp",
      aciklama: "Bukle kumaş, meşe ayak, çıkarılabilir yıkanabilir kılıf. Oturum süngeri 32 dansite.",
      olcu: "220 x 92 x 80 cm", stok: "stokta",
      secenekler: { "Kumaş": ["Adaçayı yeşili", "Krem", "Antrasit"], "Ayak": ["Doğal meşe", "Siyah"] } },
    { id: "B-110", kat: "oturma", ad: "Ada Berjer", fiyat: 12900, gorsel: "img/koltuk-berjer.webp",
      aciklama: "Masif ceviz iskelet, keten minder. Okuma köşeleri için tek kişilik.",
      olcu: "74 x 80 x 78 cm", stok: "stokta",
      secenekler: { "Minder": ["Krem keten", "Hardal", "Gri"] } },
    { id: "K-520", kat: "oturma", ad: "Nora Köşe Takımı", fiyat: 58900, gorsel: "img/kose-takimi.webp",
      aciklama: "Alçak gövdeli L köşe, uzanma modülü sağ ya da sol yapılabilir. Ölçüye göre üretim.",
      olcu: "310 x 190 x 78 cm", stok: "siparis", uretimGun: 15,
      secenekler: { "Yön": ["Uzanma sağda", "Uzanma solda"], "Kumaş": ["Sıcak gri", "Bej", "Lacivert"] } },
    { id: "Y-640", kat: "yemek", ad: "Meşe Yemek Masası + 4 Sandalye", fiyat: 42500, gorsel: "img/yemek-masasi.webp",
      aciklama: "Masif meşe tabla, 6 kişilik. Sandalyeler döşemeli, kumaş seçilebilir.",
      olcu: "Masa 180 x 90 x 76 cm", stok: "siparis", uretimGun: 20,
      secenekler: { "Sandalye kumaşı": ["Bej", "Taba", "Füme"], "Sandalye adedi": ["4", "6"] } },
    { id: "S-210", kat: "yemek", ad: "Vera Sandalye", fiyat: 4250, gorsel: "img/sandalye.webp",
      aciklama: "Kavisli sırt, kadife döşeme, meşe ayak. Tek adet fiyatıdır.",
      olcu: "48 x 54 x 82 cm", stok: "stokta",
      secenekler: { "Kumaş": ["Kiremit kadife", "Zeytin kadife", "Krem kadife"] } },
    { id: "T-180", kat: "depolama", ad: "Oluklu TV Ünitesi", fiyat: 18900, gorsel: "img/tv-unitesi.webp",
      aciklama: "Ceviz kaplama oluklu kapaklar, kablo geçişi, metal ayak. 75 inç televizyona uygun.",
      olcu: "200 x 42 x 55 cm", stok: "stokta",
      secenekler: { "Renk": ["Ceviz", "Meşe"] } },
    { id: "K-090", kat: "depolama", ad: "Loft Kitaplık", fiyat: 11200, gorsel: "img/kitaplik.webp",
      aciklama: "Siyah metal iskelet, meşe raflar. Duvara sabitleme aparatı dahil.",
      olcu: "90 x 35 x 190 cm", stok: "stokta",
      secenekler: { "Raf": ["Meşe", "Ceviz"] } },
    { id: "H-040", kat: "sehpa", ad: "Traverten Orta Sehpa", fiyat: 9750, gorsel: "img/sehpa.webp",
      aciklama: "Denizli traverteni, tek parça ayak. Doğal taş olduğu için her ürün farklı desenlidir.",
      olcu: "Ø 80 x 38 cm", stok: "stokta",
      secenekler: { "Çap": ["80 cm", "100 cm (+2.500 ₺)"] } },
    { id: "Y-160", kat: "yatak", ad: "Selin Başlıklı Karyola", fiyat: 27900, gorsel: "img/yatak.webp",
      aciklama: "Kapitoneli yüksek başlık, sandıklı taban seçeneği. Yatak dahil değildir.",
      olcu: "160 x 200 yatak için", stok: "siparis", uretimGun: 12,
      secenekler: { "Ölçü": ["160 x 200", "180 x 200 (+3.000 ₺)"], "Taban": ["Sandıklı", "Ayaklı"] } },
    { id: "Y-045", kat: "yatak", ad: "Meşe Komodin", fiyat: 5450, gorsel: "img/komodin.webp",
      aciklama: "Tek çekmeceli, alt açık raflı komodin. Meşe kaplama, frenli ray.",
      olcu: "45 x 38 x 50 cm", stok: "stokta",
      secenekler: { "Renk": ["Açık meşe", "Ceviz"] } }
  ]
};
